# Generated by Django 2.1.7 on 2019-05-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('search_engine', models.CharField(max_length=20)),
                ('keyword_search', models.CharField(max_length=20)),
                ('page_num', models.IntegerField()),
            ],
        ),
    ]
