# Generated by Django 2.1.7 on 2019-05-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
